---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  vars:
    resource:
      - godsons #resource-group
      - godsons  #storage_name
      - godsonvm  #vm_name
      - godsonvm-nsg  #nsg_name 
      - centralus #location
  tasks:
  - name: 6.4 Ensure that Network Security Group Flow Log retention period is 'greater than 90 days' (Scored) 
    command: az network watcher flow-log configure --nsg ""{{ resource[3] }}"" --enabled true --resource-group ""{{ resource[0] }}"" --retention 91 --storage-account ""{{ resource[1] }}""
    tags:
      - '6.4'
      - gpgcheck
      - one
      - all
  - name: 6.5 Ensure that Network Watcher is 'Enabled' (Scored) 
    command: az network watcher configure --location ""{{ resource[4] }}"" --enabled true --resource-group ""{{ resource[0] }}"" --tags key[=value] key[=value] 
    tags:
      - '6.5'
      - gpgcheck
      - one
      - all
  - name: Delete VM Extension
    azure_rm_virtualmachineextension:
       name: KESL
       location: centralus
       resource_group: godsons
       virtual_machine_name: godsonvm
       state: absent
